[{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 1084,
	"startColumn": 5,
	"endLineNumber": 1084,
	"endColumn": 7,
	"modelVersionId": 9,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 1085,
	"startColumn": 5,
	"endLineNumber": 1085,
	"endColumn": 7,
	"modelVersionId": 9,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1086,
	"startColumn": 3,
	"endLineNumber": 1086,
	"endColumn": 4,
	"modelVersionId": 9,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Declaration or statement expected.",
	"source": "ts",
	"startLineNumber": 1087,
	"startColumn": 1,
	"endLineNumber": 1087,
	"endColumn": 2,
	"modelVersionId": 9,
	"origin": "extHost1"
}]