[{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1002",
	"severity": 8,
	"message": "Unterminated string literal.",
	"source": "ts",
	"startLineNumber": 1049,
	"startColumn": 120,
	"endLineNumber": 1049,
	"endColumn": 120,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 1050,
	"startColumn": 1,
	"endLineNumber": 1050,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1051,
	"startColumn": 1,
	"endLineNumber": 1051,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1002",
	"severity": 8,
	"message": "Unterminated string literal.",
	"source": "ts",
	"startLineNumber": 1051,
	"startColumn": 4,
	"endLineNumber": 1051,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 1052,
	"startColumn": 21,
	"endLineNumber": 1052,
	"endColumn": 26,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 1052,
	"startColumn": 85,
	"endLineNumber": 1052,
	"endColumn": 86,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1002",
	"severity": 8,
	"message": "Unterminated string literal.",
	"source": "ts",
	"startLineNumber": 1055,
	"startColumn": 131,
	"endLineNumber": 1055,
	"endColumn": 131,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 1056,
	"startColumn": 1,
	"endLineNumber": 1056,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1057,
	"startColumn": 1,
	"endLineNumber": 1057,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1002",
	"severity": 8,
	"message": "Unterminated string literal.",
	"source": "ts",
	"startLineNumber": 1057,
	"startColumn": 4,
	"endLineNumber": 1057,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 1058,
	"startColumn": 21,
	"endLineNumber": 1058,
	"endColumn": 26,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 1058,
	"startColumn": 83,
	"endLineNumber": 1058,
	"endColumn": 84,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1002",
	"severity": 8,
	"message": "Unterminated string literal.",
	"source": "ts",
	"startLineNumber": 1061,
	"startColumn": 107,
	"endLineNumber": 1061,
	"endColumn": 107,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "':' expected.",
	"source": "ts",
	"startLineNumber": 1062,
	"startColumn": 1,
	"endLineNumber": 1062,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1063,
	"startColumn": 1,
	"endLineNumber": 1063,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1002",
	"severity": 8,
	"message": "Unterminated string literal.",
	"source": "ts",
	"startLineNumber": 1063,
	"startColumn": 4,
	"endLineNumber": 1063,
	"endColumn": 4,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "',' expected.",
	"source": "ts",
	"startLineNumber": 1064,
	"startColumn": 21,
	"endLineNumber": 1064,
	"endColumn": 26,
	"modelVersionId": 15,
	"origin": "extHost1"
},{
	"resource": "/Users/yuko/repertia/src/App.jsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "')' expected.",
	"source": "ts",
	"startLineNumber": 1064,
	"startColumn": 80,
	"endLineNumber": 1064,
	"endColumn": 81,
	"modelVersionId": 15,
	"origin": "extHost1"
}]